// Planet data - each represents a multiplication table
export const planets = [
  {
    id: 1,
    name: "Earth",
    table: 3,
    color: "bg-blue-400",
  },
  { id: 2, name: "Mars", table: 4, color: "bg-red-500" },
  {
    id: 3,
    name: "Jupiter",
    table: 5,
    color: "bg-orange-300",
  },
  {
    id: 4,
    name: "Saturn",
    table: 6,
    color: "bg-yellow-600",
  },
  {
    id: 5,
    name: "Uranus",
    table: 7,
    color: "bg-blue-300",
  },
  {
    id: 6,
    name: "Neptune",
    table: 8,
    color: "bg-blue-600",
  },
  {
    id: 7,
    name: "Pluto",
    table: 9,
    color: "bg-purple-400",
  },
  {
    id: 8,
    name: "Kepler-186f",
    table: 10,
    color: "bg-green-500",
  },
  {
    id: 9,
    name: "Trappist-1e",
    table: 11,
    color: "bg-red-300",
  },
  {
    id: 10,
    name: "Proxima Centauri b",
    table: 12,
    color: "bg-pink-400",
  },
  {
    id: 11,
    name: "HD 189733b",
    table: 13,
    color: "bg-indigo-400",
  },
  {
    id: 12,
    name: "WASP-12b",
    table: 14,
    color: "bg-purple-600",
  },
  {
    id: 13,
    name: "CoRoT-7b",
    table: 15,
    color: "bg-amber-700",
  },
  {
    id: 14,
    name: "K2-18b",
    table: 16,
    color: "bg-cyan-500",
  },
  {
    id: 15,
    name: "GJ 1214b",
    table: 17,
    color: "bg-lime-600",
  },
  {
    id: 16,
    name: "TOI-1452b",
    table: 18,
    color: "bg-teal-400",
  },
  {
    id: 17,
    name: "55 Cancri e",
    table: 19,
    color: "bg-rose-500",
  },
  {
    id: 18,
    name: "Kepler-442b",
    table: 20,
    color: "bg-emerald-600",
  },
];
